theme: jekyll-theme-cayman
title: High Tide Venice - Hi!Tide
description: Hi!Tide Venice is the official app for monitoring the tide in the city of Venice, developed in collaboration with the Istituzione Centro Previsioni e Segnalazioni Maree of Venice (ICPSM). The app allows to monitor the current tide in Venice and it provides detailed tide forecasts for the next two days.
